### ISSUE TITLE
Missing project license

### ISSUE THREAD

**Issue by tensh** [mattes/google-cloud-kms-csr#5]
Hey,

I came across this tool and it seems very useful.

Would you be OK with adding an explicit license? Without a specific license, it defaults to exclusive copyright on GitHub, meaning users are not allowed to use, modify or share the code. This even includes just running the software as is.

I see there are already several forks that adds to the work which technically is a breach unless I'm mistaken.

- The current situation from GitHubs docs: https://choosealicense.com/no-permission/
- Adding a license docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license
- StackOverflow thread on this topic: https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

The https://choosealicense.com offers you three very popular licenses a click away with a short description of what they're about.

Thanks!

**Comment by mattes** [comment]
Thanks for bringing this to my attention. ea0ce2ccb6b4757420aa56ab7cf5eba27313fd60 Done.

**Comment by tensh** [comment]
Terrific, thanks!
